# Generated by Django 5.1.6 on 2025-02-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_venta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
