# Generated by Django 5.1.6 on 2025-02-20 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_venta_cajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to='web.usuario'),
        ),
    ]
