# Generated by Django 5.2.1 on 2025-07-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_usuario_date_joined_usuario_groups_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
