# Generated by Django 5.1.6 on 2025-02-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_venta_cajero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cajero',
        ),
    ]
